-- 코드를 입력하세요
SELECT ICE.FLAVOR
FROM FIRST_HALF ICE, ICECREAM_INFO INFO
WHERE 1=1
 AND ICE.FLAVOR = INFO.FLAVOR
 AND INFO.INGREDIENT_TYPE = "fruit_based"
 AND ICE.TOTAL_ORDER > 3000
ORDER BY TOTAL_ORDER DESC