-- 코드를 입력하세요
SELECT
 BOOK_ID,
 DATE_FORMAT(PUBLISHED_DATE, '%Y-%m-%d') AS PUBLISED_DATE
FROM BOOK
WHERE 1=1
 AND CATEGORY = "인문"
 AND EXTRACT(year FROM PUBLISHED_DATE) = "2021"
ORDER BY PUBLISHED_DATE ASC